# Generated by Django 3.2.9 on 2021-12-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20211224_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
